#!/usr/bin/env python3
"""
Convert curve definitions from backend/curves/dataset/**/*.json
into the CURVE_REGISTRY format used by backend/api/curves.py.

Usage:
    python convert_to_api.py [OPTIONS]

Options:
    --dataset-dir PATH    Source directory (default: backend/curves/dataset)
    --output PATH         Output file (default: backend/api/curves.py, overwrites CURVE_REGISTRY)
    --dry-run             Print to stdout instead of writing
    --category NAME       Filter by category: general, smooth, anomalous (repeatable, all by default)
    --naming {bit,category_bit,filename_index}  Registry key style (default: category_bit)
"""

import argparse
import json
import re
import sys
from pathlib import Path


CATEGORIES = ("general", "smooth", "anomalous")

HEADER = '''\
"""
Curve registry — AUTO-GENERATED by curves/convert_to_api.py.
DO NOT EDIT MANUALLY. Run the converter to regenerate.

Add curve definitions here. Example format:

CURVE_REGISTRY = {
    "anomalous_128": {
        "name": "Anomalous 128-bit",
        "description": "Anomalous curve, vulnerable to Smart attack",
        "p": ...,
        "a": ...,
        "b": ...,
        "gx": ...,
        "gy": ...,
        "q": ...,
    },
}
"""

'''


def parse_args():
    p = argparse.ArgumentParser(
        description="Convert ecgen JSON curves to api/curves.py CURVE_REGISTRY."
    )
    p.add_argument(
        "--dataset-dir",
        default=None,
        help="Source directory containing category subfolders (default: auto-detect relative to this script)",
    )
    p.add_argument(
        "--output",
        default=None,
        help="Output file path (default: ../api/curves.py relative to this script)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated content to stdout instead of writing",
    )
    p.add_argument(
        "--category",
        action="append",
        choices=CATEGORIES,
        help="Filter by category (repeatable; default: all)",
    )
    p.add_argument(
        "--naming",
        choices=("bit", "category_bit", "filename_index"),
        default="category_bit",
        help="Registry key naming style (default: category_bit)",
    )
    return p.parse_args()


def resolve_paths(args):
    script_dir = Path(__file__).resolve().parent

    dataset_dir = Path(args.dataset_dir) if args.dataset_dir else script_dir / "production"
    if not dataset_dir.is_dir():
        print(f"Error: dataset directory not found: {dataset_dir}", file=sys.stderr)
        sys.exit(1)

    output = Path(args.output) if args.output else script_dir.parent / "api" / "curves.py"

    return dataset_dir, output


def load_curves(dataset_dir, categories):
    """Load all curve JSON files and return list of (category, filename, curve_dict) tuples."""
    curves = []
    for cat in categories:
        cat_dir = dataset_dir / cat
        if not cat_dir.is_dir():
            print(f"Warning: category directory not found: {cat_dir}", file=sys.stderr)
            continue
        for json_file in sorted(cat_dir.glob("*.json")):
            with open(json_file) as f:
                data = json.load(f)
            if not isinstance(data, list):
                print(f"Warning: expected array in {json_file}, skipping", file=sys.stderr)
                continue
            for curve in data:
                curves.append((cat, json_file.stem, curve))
    return curves


def extract_params(curve):
    """Extract api/curves.py-compatible params from an ecgen curve dict."""
    p = int(curve["field"]["p"], 16)
    a = int(curve["a"], 16)
    b = int(curve["b"], 16)
    q = int(curve["order"], 16)
    subgroups = curve.get("subgroups", [])
    if not subgroups:
        return None
    sg = subgroups[0]
    gx = int(sg["x"], 16)
    gy = int(sg["y"], 16)
    return {"p": p, "a": a, "b": b, "gx": gx, "gy": gy, "q": q}


def make_name(category, filename, index, params):
    """Build a human-readable name for the curve entry."""
    bit_label = filename.replace("bit", "bit")  # keep as-is, e.g. "16bit", "128bit"
    return f"{category.capitalize()} {bit_label} #{index}"


def make_description(category, params, filename=None): # Добавили filename в аргументы
    """Generate a short description based on category."""
    bit_size = params["q"].bit_length()
    
    if category == "anomalous":
        return f"Аномальная кривая ({bit_size}-bit), уязвимая к атаке Смарта"
    
    elif category == "smooth":
        smooth_match = re.search(r"(\d+)smooth", filename)
        smooth_val = smooth_match.group(1) if smooth_match else "unknown"
        return f"Кривая с гладким порядком ({bit_size}-bit, smooth={smooth_val}), уязвимая к атаке Похлига-Хеллмана"
    
    else:
        return f"Обычная кривая с простым порядком генератора ({bit_size}-bit) без особых уязвимостей"


def make_key(category, filename, index, naming):
    """Generate the registry key."""
    if naming == "bit":
        # Extract the bit portion from filename, e.g. "16bit" from "16bit" or "64bit16smooth"
        import re
        m = re.match(r"(\d+bit)", filename)
        bit_part = m.group(1) if m else filename
        return f"{bit_part}_{index}"
    elif naming == "category_bit":
        return f"{category}_{filename}_{index}"
    else:  # filename_index
        return f"{filename}_{index}"


def generate_registry(curves, naming):
    """Generate the CURVE_REGISTRY dict content as a string."""
    # Count occurrences per (category, filename) as we go
    counters = {}
    entries = []

    for category, filename, curve in curves:
        params = extract_params(curve)
        if params is None:
            print(f"Warning: curve in {filename} has no subgroups, skipping", file=sys.stderr)
            continue

        ck = (category, filename)
        index = counters.get(ck, 0)
        counters[ck] = index + 1

        key = make_key(category, filename, index, naming)
        name = make_name(category, filename, index, params)
        desc = make_description(category, params, filename)

        entry = (
            f'    "{key}": {{\n'
            f'        "name": "{name}",\n'
            f'        "description": "{desc}",\n'
            f'        "p": {params["p"]},\n'
            f'        "a": {params["a"]},\n'
            f'        "b": {params["b"]},\n'
            f'        "gx": {params["gx"]},\n'
            f'        "gy": {params["gy"]},\n'
            f'        "q": {params["q"]},\n'
            f"    }},"
        )
        entries.append(entry)

    if not entries:
        return HEADER + "CURVE_REGISTRY: dict = {}\n"

    body = "\n\n".join(entries)
    return HEADER + f"CURVE_REGISTRY: dict = {{\n{body}\n}}\n"


def main():
    args = parse_args()
    dataset_dir, output = resolve_paths(args)

    categories = args.category if args.category else list(CATEGORIES)

    curves = load_curves(dataset_dir, categories)
    total = len(curves)
    print(f"Found {total} curve(s) in categories: {', '.join(categories)}", file=sys.stderr)

    content = generate_registry(curves, args.naming)

    if args.dry_run:
        print(content)
        print(f"\n# {total} curve(s) converted (dry run)", file=sys.stderr)
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        with open(output, "w") as f:
            f.write(content)
        print(f"Wrote {total} curve(s) to {output}", file=sys.stderr)


if __name__ == "__main__":
    main()
